### ISSUE TITLE
[Profile] Could not edit profile

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#24] opened 2017-07-20 13:11 UTC
OS: Windows 10
username: fiherLuci
Browser: Opera

When I go to edit my profile - 
![screenshot_7](https://user-images.githubusercontent.com/19430196/28418805-c39f45c8-6d65-11e7-824b-c715c424a9ad.png)

And I change something (in this example I changed my gender from male to female cause...#feminaziRules)
After hitting "save changes" I am redirected to this page - 
![screenshot_8](https://user-images.githubusercontent.com/19430196/28418901-1944b936-6d66-11e7-9682-33391de63ed5.png)

**Comment by fiher** [comment] 2017-07-20 13:14
EDIT - Turned out that my profile was successfully changed.  

![screenshot_9](https://user-images.githubusercontent.com/19430196/28419014-73c6818c-6d66-11e7-89ac-f1c33d6a4e12.png)

**Comment by veronika793** [comment] 2017-07-20 14:06
@fiher Please review the older issues in order to avoid duplicate ones.

**Comment by veronika793** [comment] 2017-07-20 14:16
Duplicate of https://github.com/SoftUni-Internal/suls-issues-public/issues/21

**Closed** 2017-07-24 12:21 UTC
