### ISSUE TITLE
[Profile] Courses not populating properly with data.

### ISSUE THREAD

**Issue by achobanov** [SoftUni-Internal/suls-issues-public#30] opened 2017-07-20 13:52 UTC
environment: dev
username: achobanov
os: Linux Mint 18.2
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit), Firefox 54.0
screen resolution: 1920x1080
when was discovered: 07.20.2017

**Steps to reproduce**:
- Login with achobanov
- Go to `Профил` - `Обучения`
- Open each course individually to see if there is populated data.

**Expected result**:
All courses should show records, since I have participated and finished all of them with acceptable results. 
![course-data-expected](https://user-images.githubusercontent.com/1363532/28420674-8e38cc46-6d6b-11e7-8e38-ec5401200be0.png)

**Actual result**:
Most of the courses have populated data in the headers only - score and summary, but show no records, and I think they should. As can be seen on the above screenshot, some of those who do show records have some issues with the populaction, for example: "comment" field being of value "null" and having 428 Judge score (from a maximum of 400).
![course-data-actual](https://user-images.githubusercontent.com/1363532/28420757-dacd81aa-6d6b-11e7-9757-d076c35dbafa.png)

**Comment by achobanov** [comment] 2017-07-21 08:32
**Update**:
As of now no courses listed under my account show any records at all. The data in the header still stands.

**Comment by veronika793** [comment] 2017-07-24 12:32
Duplicate of https://github.com/SoftUni-Internal/suls-issues-public/issues/1

**Closed by veronika793** 2017-07-24 12:32 UTC
