### ISSUE TITLE
C#Advanced course missing images

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#103] opened 2017-10-27 12:25 UTC
# Expected Behavior
The user must be able to see the relevant image for the selected course.

# Actual Behavior
The image (icon) for the courses C#Advanced 2017 are missing. Only label is available.
![image](https://user-images.githubusercontent.com/25150497/32103908-0743d4b6-bb2b-11e7-9548-715f0c237cf0.png)

# Preconditions
The user must be logged in.

# Steps to Reproduce
1. Navigate to https://softuni.bg/courses/csharp-advanced
2. Observe the first two courses in Archive.

# Specifications

- Platform: [What platform are you using? **SoftUni (https://softuni.org) / Software University (https://softuni.bg)**
- Browser used: Chrome 62.0.3202.75 (Official Build) (64-bit)
- URL: https://softuni.bg/courses/csharp-advanced
- Username: Iliev88

**Comment by rozay** [comment] 2017-10-31 15:59
@Iliev88 Thanks for the report, the issue is assigned to the corresponding team and will be fixed ASAP :)

**Closed as completed** 2018-06-15 21:39 UTC
Labels: Software University
