### ISSUE TITLE
[Footer] - There is a MasterCard link that redirects to nowhere

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#56] opened 2017-07-21 05:55 UTC
Enviorment - both dev and prod
Browser - Opera

When I go to the footer there is Visa and Mastercard images. The second one (Mastercard) can be clicked. When clicked on it redirects to nowhere. Here is the result

![screenshot_8](https://user-images.githubusercontent.com/19430196/28450768-1a22f854-6df2-11e7-8780-d464e9cd3f99.png)

Now if it is not clear abot which button I am talking about here is an image of it -

![screenshot_9](https://user-images.githubusercontent.com/19430196/28450788-432711d6-6df2-11e7-9923-1a5d34eb80f6.png)

Expected behavior - to redirect to an actual page or not be clickable at all as Visa.

Actual behavior - I can click it and it gives error.

**Comment by TsenkoTsenov** [comment] 2017-08-02 12:43
Right now it works fine and could not reproduce it. I am closing the issue, please check it again and let us know if the problem persists. Thank you for your report.

**Closed by TsenkoTsenov** 2017-08-02 12:43 UTC
Labels: priority: trivial
