### ISSUE TITLE
[Profile] Team-mates are in a mess when the screen is zoomed in

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#60] opened 2017-07-22 11:29 UTC
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** trivial

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "Courses"
4. Click on "Open courses"
5. Click on "QA Automation"
6. Click on "Teamwork"

**actual result**
When screen is **zoomed in (more than 110%)** the team-mates are in a mess on the screen.

**expected result**
All team-mates must be listed in a good order no matter how much the screen is zoomed in.

![teamwork-zoomin](https://user-images.githubusercontent.com/25150497/28490718-c6df5c8e-6ee9-11e7-8bfb-a4f5b72344dc.png)

**Comment by veronika793** [comment] 2017-07-24 13:09
Duplicate of https://github.com/SoftUni-Internal/suls-issues-public/issues/8

**Closed by veronika793** 2017-07-24 13:09 UTC
